//This file is ony here to get around Discord's circular dependencies
type client
type channel
type role
type guild
type guildManager
type roleManager
type guildMemberRoleManager
type guildMember
type user
type message
type messageAttachment
type messageEmbed
type reaction
type reactionManager
type reactionCollector
type emoji
type interaction
type applicationCommandManager
type slashCommandBuilder
type slashCommandStringOption
type messageActionRow
type messageButton
type commandInteractionOptionResolver
type permissions
